config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  root "home#index"

  
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts
  resources :followers
  resources :likes
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord

  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'
end

app/models/follower.rb
class Follower < ApplicationRecord
    # belongs_to :user
  belongs_to :follower, foreign_key: "follower_id", class_name: "User"
  belongs_to :followee, foreign_key: "followee_id", class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    has_one_attached :picture
    has_many :likes
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
  

  has_one_attached :avatar


  has_many :follower_follows, foreign_key: "followee_id", class_name: "Follower" 
  has_many :followers, through: :follower_follows

  has_many :followee_follows, foreign_key: "follower_id", class_name: "Follower"    
  has_many :followees, through: :followee_follows

  has_many :likes 
  has_many :comments
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def index 
        @comments = Comment.all
    end

    def show 
        @comment = Comment.find(params[:id])
    end

    def new 
        @comment = Comment.new
    end

    def create
        @post = Post.find(params[:post_id].keys.first.to_i)
        @comment = Comment.new({user_id: current_user.id, post_id: params[:post_id].keys.first.to_i, message: params[:message]})
        if @comment.save
            redirect_to user_path(@post.user)
        end
    end

    # def delete 
    #     @comment = Comment.find(params[:id])
    #     @comment.destroy(comment_params)
    # end

    private
    def comment_params 
        params.require(:comment).permit(:message, :user_id, :post_id)
    end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    skip_before_action :verify_authenticity_token

    
    def index 
        @likes = Like.all
    end

    def show 
        @like = Like.find(params[:id])
    end

    def new 
        @like = Like.new
    end

    def create 
        @like = Like.new(user_id: current_user.id, post_id: params[:post_id])
        if @like.save
            render :json => {:status => "ok"}
        end
    end

    def edit 
        @like = Like.find(params[:id])
    end

    def update 
        @like = Like.find(params[:id])
        @like.update(like_params)

        redirect_to like_path(@like)
    end

    def delete 
        @like= Like.find(params[:id])
        @like.destroy
    end

    private

    def like_params
        params.require(:like).permit(:user_id, post_id)
    end
         
         
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def add_index 
        @posts = Post.all
    end

    def show 
        @post = Post.find(params[:id])
    end

    def new 
        @post = Post.new
    end

    def create 
       @post = Post.new(description: params[:post][:description], location: params[:post][:location], user_id: current_user.id)
       @post.picture.attach(params[:post][:picture])
       if @post.save 
        redirect_to current_user
       else
        render :new
       end
    end

    def edit 
        @post = Post.find(params[:id])
    end

    def update 
        @post = Post.find(params[:id])
        @post.update(post_params)
        if @post.save
            redirect_to post_path(@post)
        else
            render :edit
        end
    end
    
    def destroy 
        Post.find(params[:id]).destroy
    end

    private
    def post_params 
        params.require(:post).permit(:description, :location, :user_id, :picture)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
 
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

      if @user.save
        redirect_to user_path(@user)
      else
        render :new
    end
  end

  def update
    if params[:user][:avatar]
      @user.avatar.attach(params[:user][:avatar])
    end
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end




  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :full_name, :user_name, :user_bio, :avatar, :phone_number, :website, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def time_ago_in_words(from_time, include_seconds_or_options = {})
        distance_of_time_in_words(from_time, Time.now, include_seconds_or_options)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>All Comments</h1>
<%@comments.each do |comment|%>
<%=comment%>
<%end%>

app/views/comments/new.html.erb
<%= form_for @comment do |f|%>
    <%=f.label :message%>
    <%=f.text_area :message%>
    <br>
    <%=f.submit "Create comment"%>
    <%end%>

app/views/comments/show.html.erb
<h1>Comment</h1>
<h4>Comment message: <%=@comment.message%></h4>

app/views/likes/edit.html.erb
<%=form_for @like do |f|%>
    <%=f.label :message%>
    <%=f.text_area :message%>
    <br>

    <%=f.submit "Edit like"%>
    <%end%>

app/views/likes/index.html.erb
<h1>All Likes</h1>

<% @likes.each do |like| %>
<%= like %>
<%end%>

app/views/likes/new.html.erb
<%= form_for @like do |f|%>
    <%=f.label :message%>
    <%=f.text_area :message%>
    <br>

     <%=f.submit "Create Like"%>
    <%end%>

app/views/likes/show.html.erb
<h1>Show Page</h1>

<h4>Message: <%=@like.message%></h4>

app/views/posts/edit.html.erb
<%=form_for @post do |f|%>
    <%=f.label :description%>
    <%=f.text_field :description%>
    <br>
    <%=f.label :location%>
    <%=f.text_field :location%>
    <br>

    <%=f.submit "Edit Post"%>
    <%end%>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<% @posts.each do |post| %>
<%= post %>
<%end%>

app/views/posts/new.html.erb
<%= form_for @post do |f|%>
    <%=f.label :description%>
    <%=f.text_field :description%>
    <br>
    <%=f.label :location%>
    <%=f.text_field :location%>
    <br>
    <%= f.file_field :picture %>
    


    <%=f.submit "Create Post"%>
    <%end%>

app/views/posts/show.html.erb
<h1>Post</h1>
<h4>Post Description: <%=@post.description%></h4>
<h4>Post Location: <%=@post.location%></h4>
<%= image_tag(url_for(@post.picture), size: "80x80", class: "round")  %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<!-- <%= render 'form', user: @user %> -->
<% if @user.avatar_attachment %>
          <%= image_tag(url_for(@user.avatar), size: "40x40", class: "round")  %>
        <% else %>
          <%= image_tag(image_url('default.jpg'), size: "40x40", class: "round") %>
        <% end %>
<strong><%= @user.user_name %></strong>


<%= form_for(@user)  do |f| %>
   <%= f.file_field :avatar %>
   <br>

   <%= f.label :full_name %>
   <%= f.text_field :full_name %>
   <br>

   <%= f.label :user_name %>
   <%= f.text_field :user_name %>
   <br>

   <%= f.label :website %>
   <%= f.text_field :website %>
   <br>

   <%= f.label :user_bio %>
   <%= f.text_area :user_bio %>
   <br>

   <%= f.label :email %>
   <%= f.text_field :email %>
   <br>

   <%= f.label :phone_number %>
   <%= f.text_field :phone_number %>
   <br>

   <%= f.label :gender %>
   <%= f.text_field :gender %>
   <br>
   <br>
   <%= f.submit %>
 <% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>


 <%= form_tag("/users") do %>
   <%= label_tag('user[email]', "Email") %>
   <%= text_field_tag('user[email]') %>
   <br>
   <%= label_tag('user[full_name]', "Name") %>
   <%= text_field_tag('user[full_name]') %>
   <br>
  
   <%= label_tag('user[user_name]', "Username") %>
   <%= text_field_tag('user[user_name]') %>
   <br>
  
    <%= label_tag('user[password]', "Password") %>
   <%= text_field_tag('user[password]') %>

   <%= submit_tag "Create User" %>
 <% end %>


<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<main>
  <div class="container">
    <div class="row headerContent">
    <div class="col left">
      <div class="image">
        <% if @user.avatar_attachment %>
          <%= image_tag(url_for(@user.avatar), size: "150x150", class: "round")  %>
        <% else %>
          <%= image_tag(image_url('default.jpg'), size: "150x150", class: "round") %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-8 right">
      <div class="content">
        <div class="row" style="max-width: 300px; margin-left: 0; ">
          <h1 style="font-weight: 200; float: left; margin-right: 25px"><%= @user.user_name %></h1>
          <% if current_user.id == @user.id %>
            <%= button_to "Edit Profile", edit_user_path(current_user), class: "customButton", method: "get" %>
          <% elsif current_user.followees.include?(@user) %>
            <%= button_to "Unfollow", follower_path(@user.id), class: "customButton", method: "delete" %>
          <% else %>
            <%= button_to "Follow", followers_path, class: "customButton", method: "post", params: { id: @user.id } %>
          <% end %>
        </div>
        <div class="row" style="max-width: 400px">
        <div class="col">
        <span><%= @user.posts.length %> posts</span>
        </div>
        <div class="col">
        <span><%= @user.followers.length %> followers</span>
        </div>
        <div class="col">
        <span><%=@user.followees.length%> following</span>
        </div>
        </div>
        <p><%= @user.full_name %></p>
        <p><%= @user.user_bio ? @user.user_bio : nil%></p>
      </div>
    </div>
    </div>
  </div>
  <section>
    <div class="container">
      <div class="row">

        <% if @user.posts %>
          <% @user.posts.each_with_index do |post, index| %>
            <div class="col-lg-4 col-md-4 item " style="margin-bottom: 25px" >
              <div class="contentSpan">
                <span class="fas fa-heart">   <%= post.likes.length %></span>
                <span class="fas fa-comment" style="margin-left: 25px;">   <%= post.comments.length %></span>
              </div>
              <%= image_tag(url_for(post.picture), class: "img-fluid image custom-image darken")%>
            </div>

            <div class="modal fade lg" id="myModal<%= index %>" role="dialog" >
              <div class="modal-dialog " style="min-width: 940px; min-height: 600px">
                <div class="modal-content" style="min-height: 600px">
                  <div class="modal-header">
                    <button type="button" class="close" id="close<%= index %>" data-dismiss="modal">&times;</button>
                  </div>
                  <div class="modal-body">
                    <div class="row">
                      <div class="col-lg-8">
                        <%= image_tag(url_for(post.picture), class: "img-fluid")%>
                      </div>
                      <div class="col-lg-4">
                        <%= image_tag(url_for(@user.avatar), class: 'round', size: "32x32") %>
                        <span class="user_name" style="margin-bottom: 15px; "><%=@user.user_name%></span>
                        <div class="row">
                          <div class="col-lg-12">
                            <span class="user_name"><%= @user.user_name %></span>
                            <span><%= post.description %></span>
                            <p class="timePtag"> <%= time_ago_in_words(post.created_at)%> ago</p>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-lg-12">
                            <% if !post.comments.empty? %>
                              <% post.comments.each do |comment| %>
                                <div class="row" style="margin-top: 15px">
                                  <div class="col-lg-2">
                                    <%= image_tag(url_for(comment.user.avatar), class: 'round', size: "32x32") %>
                                  </div>
                                  <div class="col-lg-10">
                                    <span class="user_name"><%= comment.user.user_name %></span>
                                    <span><%= comment.message %></span>
                                  </div>
                                </div>
                              <% end %>
                            <% end %>
                          </div>
                        </div>
                        <div class="row modalBottom">
                          <div class="col-lg-12">
                              <span class="far fa-heart modalIcon" post_id="<%=post.id%>" id="newLike<%=index%>" liked="false">
                              </span>
                            <span class="far fa-comment modalIcon"></span>
                            <br>
                            <span class="user_name likeCounter"><%= post.likes.length %> likes</span>
                            <br>
                            <span class="timePtag" style="font-size: 12px"><%= post.created_at.day %> <%= Date::MONTHNAMES[post.created_at.month] %></span>
                            <div class="postPart" style="bottom: -125px; position: relative;">
                              <%= form_tag("/comments") do %>
                                
                                <span><%= text_field_tag('message', nil, placeholder: 'Add a comment...') %></span>
                                <span><%= submit_tag "Post" %></span>
                                <%= hidden_field(:post_id, "#{post.id}") %>
                              <% end %>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    
                  </div>
                </div>
              </div>
            </div>
          <% end %> 
        <% end %>
      </div>
    </div>
    </section>
</main>